# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QHBoxLayout, QWidget


class Ui_ContactSelector(object):
    def setupUi(self, ContactSelector):
        ContactSelector.setObjectName("ContactSelector")
        ContactSelector.resize(400, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(ContactSelector)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelSearch = QtWidgets.QLabel(parent=ContactSelector)
        self.labelSearch.setObjectName("labelSearch")
        self.verticalLayout.addWidget(self.labelSearch)
        self.lineEditSearch = QtWidgets.QLineEdit(parent=ContactSelector)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.verticalLayout.addWidget(self.lineEditSearch)
        self.listWidgetContacts = QtWidgets.QListWidget(parent=ContactSelector)
        self.listWidgetContacts.setAlternatingRowColors(True)
        self.listWidgetContacts.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.listWidgetContacts.setObjectName("listWidgetContacts")
        self.verticalLayout.addWidget(self.listWidgetContacts)
        self.horizontalLayoutButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutButtons.setObjectName("horizontalLayoutButtons")
        self.pushButtonSelect = QtWidgets.QPushButton(parent=ContactSelector)
        self.pushButtonSelect.setStyleSheet("\n"
                                            "         QPushButton {\n"
                                            "          background-color: #4CAF50;\n"
                                            "          color: white;\n"
                                            "          border: none;\n"
                                            "          padding: 10px 20px;\n"
                                            "          font-size: 14px;\n"
                                            "          border-radius: 4px;\n"
                                            "         }\n"
                                            "         QPushButton:hover {\n"
                                            "          background-color: #45a049;\n"
                                            "         }\n"
                                            "        ")
        self.pushButtonSelect.setObjectName("pushButtonSelect")
        self.horizontalLayoutButtons.addWidget(self.pushButtonSelect)
        self.pushButtonCancel = QtWidgets.QPushButton(parent=ContactSelector)
        self.pushButtonCancel.setStyleSheet("\n"
                                            "         QPushButton {\n"
                                            "          background-color: #f44336;\n"
                                            "          color: white;\n"
                                            "          border: none;\n"
                                            "          padding: 10px 20px;\n"
                                            "          font-size: 14px;\n"
                                            "          border-radius: 4px;\n"
                                            "         }\n"
                                            "         QPushButton:hover {\n"
                                            "          background-color: #d32f2f;\n"
                                            "         }\n"
                                            "        ")
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayoutButtons.addWidget(self.pushButtonCancel)
        button_container = QWidget()
        button_layout = QHBoxLayout(button_container)
        button_layout.setContentsMargins(0, 0, 0, 0)
        button_layout.addWidget(self.pushButtonSelect)
        button_layout.addWidget(self.pushButtonCancel)
        button_layout.addStretch()
        self.verticalLayout.addWidget(button_container)

        self.retranslateUi(ContactSelector)
        QtCore.QMetaObject.connectSlotsByName(ContactSelector)

    def retranslateUi(self, ContactSelector):
        _translate = QtCore.QCoreApplication.translate
        ContactSelector.setWindowTitle(_translate("ContactSelector", "Выбор контакта"))
        self.labelSearch.setText(_translate("ContactSelector", "Поиск контакта:"))
        self.lineEditSearch.setPlaceholderText(_translate("ContactSelector", "Введите имя или email"))
        self.pushButtonSelect.setText(_translate("ContactSelector", "Выбрать"))
        self.pushButtonCancel.setText(_translate("ContactSelector", "Отмена"))
